name: Terraform Associate 004 Recap

on: push

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: List Files
      run: ls

    